### ISSUE TITLE
Implement A-star

### ISSUE THREAD

**Issue by rene-scheepers** [rene-scheepers/case-life#1]
* Change the way the world works.
 * World should be responsible for the location of the objects, not the object itself.
 * Locations should be removed.
 * Locations should be replaced with the hashmap but now only the LocationType.
* Implement weighted graph.
* All animals should avoid all omnivores and carnivores unless it is a pack animal.
* Herbivores and omnivores must be attracted to plants.

* Implement interfaces for pathfinding.
* Have animals determine path using the pathfinder.
* Make animals choose most desirable destination based on current state. (Hunger, energy, etc...)

**Comment by Measuring** [comment]
http://theory.stanford.edu/~amitp/GameProgramming/ :dancers:
